Fix novendorchange option
openSUSE/salt pull request #284
Opened 2020-10-19 21:47 UTC by mseidl

### What does this PR do?

Fixes the novendorchange option in zypper... 

### What issues does this PR fix or reference?
Fixes: No issue number

### Previous Behavior
What happens with novendorchange is: the option of "--no-allow-change" is visible or not.  The issue is, in zypper vendor changes are not allowed by default. So, the the behavior between "zypper dup --no-allow-vendor-change" and "zypper dup" is nothing... 

### New Behavior
Now adds --allow-vendor-change 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2020-10-20 13:31 UTC, brejoc requested changes

2020-10-20 13:31 UTC, brejoc commented on salt/modules/zypperpkg.py
> +    """
I think you are mixing double and single quote here.

2020-10-23 09:56 UTC, meaksh requested changes

2020-10-23 09:56 UTC, meaksh commented on salt/modules/zypperpkg.py
> +    """
@mseidl this change (the double quotes) must be removed here since it's breaking the doc string.
```suggestion
    '''
```

2020-10-26 08:49 UTC, meaksh approved these changes

2020-10-27 15:12 UTC, merged