Add Alibaba Cloud Linux 2 to Salt 3000 branch
openSUSE/salt pull request #351
Opened 2021-04-04 00:55 UTC by paususe

### What does this PR do?

Adds Alibaba Cloud Linux to Salt 3000.0 branch

### What issues does this PR fix or reference?

Backport of https://github.com/saltstack/salt/pull/59687

### Previous Behavior

I had implemented my own grain while implementing support for Alibaba Cloud Linux 2 in Uyuni, but only a few days ago, an official grain coming from Alibaba was merged upstream.

### New Behavior

Same as upstream.

### Tests written?

Yes (unit test)

### Commits signed with GPG?

No

2021-04-04 01:02 UTC, paususe commented
@meaksh could you please review and merge?

2021-04-05 14:25 UTC, meaksh approved these changes

2021-04-09 08:18 UTC, meaksh requested changes
@paususe it seems this PR is making some extra changes related to github actions configuration and there is also a unit test failing.

Could you please take a look? Thanks

2021-04-09 09:29 UTC, meaksh commented
@paususe I think you need to rebase your changes with latest `openSUSE-3000` since there a force push to that branch.

2021-04-13 20:24 UTC, paususe commented
> @paususe I think you need to rebase your changes with latest `openSUSE-3000` since there a force push to that branch.

Done

2021-04-14 09:19 UTC, meaksh requested changes

2021-04-14 09:19 UTC, meaksh commented on tests/unit/grains/test_core.py
> +            "_linux_distribution": ("alinux", "2.1903", "LTS"),
@paususe this should fix the failure of the unit test:

```suggestion
            "linux_distribution": ("alinux", "2.1903", "LTS"),
```

2021-04-14 11:29 UTC, meaksh approved these changes

2021-04-14 11:29 UTC, merged