Fix x509 test fails on old openssl systems
openSUSE/salt pull request #682
Opened 2024-09-24 11:51 UTC by m-czernek

### What does this PR do?

This PR fixes our failing x509 tests on SLES12SP5 and CentOS7.

### What issues does this PR fix or reference?
Relates to: https://github.com/SUSE/spacewalk/issues/23286

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2024-09-26 08:05 UTC, vzhestkov requested changes
Explicit check for OpenSSL version looks bit redundant here, with the latest alignments for pyopenssl module I've fixed the case when there was a segfault erros on calling certain calls and as a result the test ends unexpectedly with ERROR or FAIL, but with such checks for the version before calling the test we can hide such segfaults.

2024-09-26 11:58 UTC, m-czernek commented
@vzhestkov we are only skipping execution on unsupported algorithms, which are: `ec`, `ed25519`, and `ed448`. If a test uses the `@pytest.mark.skipif` annotation, it's because it hardcodes an unsupported algorithm.

In other words, tests that are currently passing on the older openssl version are not skipped.

Previously, we had a hacky "run the test, and skip it based on a specific exception" solution. However, this is a problem because not all tests provide nice exception. For example, I think some tests that used the `ed25519` and `ed448` algorithms simply failed to read a PEM key (which failed to be created due to an unsupported algorithm).

With that in mind, do you still object to the solution? Would you prefer to do the "run the code, skip based on the exception" approach? Or is there another solution that you can think of?

2024-09-27 09:15 UTC, m-czernek commented
Ack. This should be more in line with your views @vzhestkov :)

2024-09-30 07:17 UTC, vzhestkov approved these changes
Thanks for adjusting and taking care of it :+1:

2024-10-02 07:09 UTC, merged